# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: data-kafka-zookeeper-0
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: data-kafka-broker-0
# spec:
#   capacity:
#     storage: 8Gi
#   volumeMode: Filesystem
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: data-kafka-zookeeper-1
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: data-kafka-broker-1
# spec:
#   capacity:
#     storage: 8Gi
#   volumeMode: Filesystem
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: data-kafka-zookeeper-2
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: data-kafka-broker-2
# spec:
#   capacity:
#     storage: 8Gi
#   volumeMode: Filesystem
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-broker-0
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-broker-1
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-broker-2
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-zookeeper-0
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-zookeeper-1
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-zookeeper-2
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
